# Generated by Django 3.0.8 on 2022-03-30 06:42

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='分类')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=50, unique=True, verbose_name='课程id')),
                ('name', models.CharField(max_length=100, verbose_name='课程名')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='课程介绍')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容')),
                ('url', models.URLField(blank=True, null=True, verbose_name='课程地址')),
                ('prerequisites', models.CharField(blank=True, max_length=100, null=True, verbose_name='先修课程')),
                ('img', models.ImageField(blank=True, null=True, upload_to='course_img/%Y/%m/%d/', verbose_name='课程图片')),
                ('user_num', models.PositiveIntegerField(default=0, verbose_name='选课人数')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Category')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sch_id', models.CharField(max_length=50, unique=True, verbose_name='学校id')),
                ('name', models.CharField(max_length=100, verbose_name='学校名')),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='学校介绍')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程标签')),
            ],
            options={
                'verbose_name': '课程标签',
                'verbose_name_plural': '课程标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('u_id', models.CharField(max_length=20, unique=True, verbose_name='用户id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 3, 30, 6, 42, 48, 496443, tzinfo=utc), verbose_name='选课日期')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最近修改日期')),
                ('state', models.BooleanField(default=True, verbose_name='选课状态')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course', to_field='course_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.User')),
            ],
            options={
                'verbose_name': '选课关系',
                'verbose_name_plural': '选课关系',
                'db_table': 'user_course',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('t_id', models.CharField(max_length=50, unique=True, verbose_name='教师id')),
                ('name', models.CharField(max_length=100, verbose_name='教师名')),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='教师介绍')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.School', to_field='sch_id', verbose_name='任职学校')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 3, 30, 6, 42, 48, 497437, tzinfo=utc), verbose_name='推荐日期')),
                ('recommend_type', models.CharField(blank=True, choices=[('hot', 'hot'), ('custom', 'customized')], max_length=10, null=True)),
                ('recommend_cycle', models.CharField(blank=True, choices=[('hot', 'hot'), ('custom', 'customized')], max_length=10, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course', to_field='course_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.User', to_field='u_id')),
            ],
            options={
                'verbose_name': '推荐结果',
                'verbose_name_plural': '推荐结果',
                'db_table': 'recommend',
            },
        ),
    ]
