# Generated by Django 3.0.8 on 2022-03-30 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 6, 44, 15, 407403, tzinfo=utc), verbose_name='推荐日期'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 6, 44, 15, 406405, tzinfo=utc), verbose_name='选课日期'),
        ),
    ]
