# Generated by Django 3.0.8 on 2022-03-29 10:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=50, unique=True, verbose_name='课程id')),
                ('name', models.CharField(max_length=100, verbose_name='课程名')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='课程介绍')),
                ('url', models.URLField(blank=True, null=True, verbose_name='课程地址')),
                ('prerequisites', models.CharField(blank=True, max_length=100, null=True, verbose_name='先修课程')),
                ('img', models.ImageField(blank=True, null=True, upload_to='course_img/%Y/%m/%d/', verbose_name='课程图片')),
                ('user_num', models.PositiveIntegerField(default=0, verbose_name='选课人数')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Category')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sch_id', models.CharField(max_length=50, unique=True, verbose_name='学校id')),
                ('name', models.CharField(max_length=100, verbose_name='学校名')),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='学校介绍')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 3, 29, 10, 12, 18, 838024, tzinfo=utc), verbose_name='选课日期')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最近修改日期')),
                ('state', models.BooleanField(default=True, verbose_name='选课状态')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.User')),
            ],
            options={
                'verbose_name': '选课关系',
                'verbose_name_plural': '选课关系',
                'db_table': 'user_course',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('t_id', models.CharField(max_length=50, unique=True, verbose_name='教师id')),
                ('name', models.CharField(max_length=100, verbose_name='教师名')),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='教师介绍')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.School', verbose_name='任职学校')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teacher',
            },
        ),
    ]
