# Generated by Django 3.0.8 on 2022-03-30 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220330_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 6, 58, 39, 635629, tzinfo=utc), verbose_name='推荐日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 6, 58, 39, 632637, tzinfo=utc), verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 6, 58, 39, 634632, tzinfo=utc), verbose_name='选课日期'),
        ),
    ]
