# Generated by Django 3.0.8 on 2022-03-29 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220329_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 10, 23, 39, 107341, tzinfo=utc), verbose_name='选课日期'),
        ),
    ]
