# Generated by Django 3.0.8 on 2022-03-29 10:26

import DjangoUeditor.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20220329_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 10, 26, 9, 409210, tzinfo=utc), verbose_name='选课日期'),
        ),
    ]
