# Generated by Django 3.0.8 on 2022-04-01 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20220401_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 6, 25, 8, 432252, tzinfo=utc), verbose_name='推荐日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 6, 25, 8, 430258, tzinfo=utc), verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 6, 25, 8, 431257, tzinfo=utc), null=True, verbose_name='选课日期'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.User', to_field='u_id'),
        ),
    ]
