# Generated by Django 3.0.8 on 2022-04-02 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20220401_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 2, 10, 33, 33, 285669, tzinfo=utc), null=True, verbose_name='创建课程时间'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 10, 33, 33, 287667, tzinfo=utc), verbose_name='推荐日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 10, 33, 33, 284672, tzinfo=utc), verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 10, 33, 33, 286673, tzinfo=utc), null=True, verbose_name='选课日期'),
        ),
    ]
